[build]
  command = "pnpm build:web" 
  publish = ".next"

[dev]
  command = "pnpm run dev" # Or your dev command
  port = 3000
  targetPort = 3000 # If needed

[[plugins]]
  package = "@netlify/plugin-nextjs"
