[build]
  command = "cd apps/api && pnpm build && mkdir -p ../../../netlify/functions && cp -r ./dist/* ../../../netlify/functions"
  publish = "netlify/functions" 

[dev]
  command = "pnpm build && pnpm start"
  port = 3000 

[functions]
  directory = "netlify/functions"