[build]
  command = "tsc apps/api/index.ts --outfile netlify/functions/index.js && cp apps/api/abi.js netlify/functions/"
  publish = "netlify/functions"

[dev]
  command = "pnpm build && pnpm start"
  port = 3000 

[functions]
  directory = "netlify/functions"