name: Lint and e2e tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
        working-directory: apps/web
      - name: Install Playwright Browsers
        run: npx playwright install-deps
        working-directory: apps/web
      - name: Run linting
        run: pnpm run lint
        working-directory: apps/web
      - name: Start Next.js server
        run: pnpm run dev &
        working-directory: apps/web
      - name: Wait for server to start
        run: npx wait-on http://localhost:3000
      - name: Run Playwright tests
        run: npx playwright test
        working-directory: apps/web
